
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from info import dysplay
from dettagli import dysplay1
import webbrowser
from api import give_data
OUTPUT_PATH = Path(__file__).parent  # Questo punta alla cartella "build"
ASSETS_PATH = OUTPUT_PATH / "assets" / "frame0"  # Percorso relativo al file



def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_link(url):
    """Apre il link specificato nel browser predefinito."""
    webbrowser.open(url)

window = Tk()
window.title("People in the space")

window.geometry("1172x694")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 694,
    width = 1172,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    586.0,
    347.0,
    image=image_image_1
)

canvas.create_text(
    14.0,
    643.0,
    anchor="nw",
    text="Made By Giacomo Rossi",
    fill="#F5F5F5",
    font=("Courier", 40 * -1)
)

canvas.create_text(
    829.0,
    639.0,
    anchor="nw",
    text="Documentation",
    fill="#F5F5F5",
    font=("Courier", 40 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    1012.0,
    200.0,
    image=image_image_2
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_link("https://github.com/Arrow-07/People-in-the-space"),
    relief="flat"
)
button_1.place(
    x=774.0,
    y=638.0,
    width=48.0,
    height=48.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    587.0,
    362.0,
    image=image_image_3
)

canvas.create_text(
    31.0,
    50.0,
    anchor="nw",
    text="People in the space",
    fill="#7EB5DF",
    font=("Courier", 65 * -1)
)

canvas.create_text(
    279.0,
    224.0,
    anchor="nw",
    text="Number of\npeople:\n",
    fill="#295DCD",
    font=("Courier", 64 * -1)
)



people_count_text = canvas.create_text(
    702.0,
    260.0,
    anchor="nw",
    text=str(give_data("number")),
    fill="#7EB5DF",
    font=("Courier", 96 * -1)
)


canvas.create_text(
    318.0,
    419.0,
    anchor="nw",
    text="Names & Details",
    fill="#295DCD",
    font=("Courier", 40 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=dysplay,
    relief="flat"
)
button_2.place(
    x=710.0,
    y=414.0,
    width=48.0,
    height=48.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=dysplay1,
    relief="flat"
)
button_3.place(
    x=266.0,
    y=419.0,
    width=52.0,
    height=52.0
)

canvas.create_text(
    758.0,
    428.0,
    anchor="nw",
    text="Info",
    fill="#295DCD",
    font=("Courier", 40 * -1)
)
window.resizable(False, False)
window.mainloop()
